### ISSUE TITLE
Auth - Response Code check

### ISSUE THREAD

**Issue by OnceUponALoop** [pigskin/pigskin#26]
Not an issue - just a question.

Alex, this project is pretty awesome man 👍 you're taking this from a limited use script to a full blown API and I for one can't wait.

I've been working on the kodi add-on side of things, would you be ok with some refactoring there? 

I was looking over pigskin and i'm wondering why you don't check the response codes before attempting to parse the data and instead rely on exceptions? Is there an advantage to exceptions over validation (speed?).
It would just make it easier to log if we can distinguish between invalid/unparsable responses vs. auth issues.

Ex. from _gp_auth
``` python
try:
    r = self.http_session.post(url, data=post_data)
    self._log_request(r)
    # Invalid response, just return
    if r.status_code != requests.codes.ok:
        self.logger.warning('Login unsuccessful. Status code: {status_code}'.format(status_code=r.status_code))
        return {}
    else:
    data = r.json()

    # make sure auth data is there
    for key in ['access_token', 'refresh_token']:
        if not data.get(key):
            self.logger.error('could not parse auth response')
            return {}

except ValueError:
    self.logger.error('_gp_auth: server response is invalid')
    return {}

return data
```

**Comment by aqw** [comment]
@OnceUponALoop Thanks for the compliments. :-) I just wish I had more time!

As for your question: there's no special reason I don't check for response codes; I just havn't gotten to it yet. There's a few todo/comments around saying I should add exactly that, and I would like it to be a feature of all requests.

So if you're motivated, submit a patch and I'll be happy to merge it. :-)

One thing that I wonder is whether this should be added as boilerplate to every function/method, or if there's a way a callback can be (sanely) added to the session handle, so that it becomes a standard feature of all connections. I'm not if such a setup would even be useful, but is something I was considering. Going that route opens up lots of possibilities beyond error checking, such as retries, logging, filtering, etc. So it's a bit of a rabbit hole. ;-)

Thanks for the question, and if you have the time and energy, it would be great to see a PR. :-D

---Alex

**Comment by jm-duke** [comment]
I thought about this topic myself.

@aqw what do you think about extending the store() class? Like adding get() and post() methods to handle HTTP requests. Exceptions and HTTP errors would be handled there as well.

**Comment by aqw** [comment]
Hey @jm-duke,

It's been awhile since I looked at this, but I think we can avoid having to extend the store class, since it's already contains the handle to the requests session. I /think/ we can just wrap/decorate/whatever the session handle, and it'll do everything we need to.

I think that would be the preferred solution (assuming it's possible). But if you find another way that you like and think is clean, then I'm all for it. :-)

---Alex

**Comment by jm-duke** [comment]
Closing this issue, as NFL has canceled the Gamepass service
